
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.filepath.k8s.io
  labels:
    api: non-etcd
    apiserver: "true"
spec:
  version: v1
  group: filepath.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: non-etcd
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhVENDQWxHZ0F3SUJBZ0lKQVBHUEo3ZDFRY0lZTUEwR0NTcUdTSWIzRFFFQkN3VUFNR2d4Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhKekFsQmdOVkJBTU1IbTV2YmkxbGRHTmtMV05sY25ScFptbGpZWFJsTFdGMWRHaHZjbWwwCmVUQWVGdzB5TVRBME1qa3hNREF3TVRKYUZ3MHlNakEwTWpreE1EQXdNVEphTUdneEN6QUpCZ05WQkFZVEFuVnUKTVFzd0NRWURWUVFJREFKemRERUtNQWdHQTFVRUJ3d0JiREVLTUFnR0ExVUVDZ3dCYnpFTE1Ba0dBMVVFQ3d3QwpiM1V4SnpBbEJnTlZCQU1NSG01dmJpMWxkR05rTFdObGNuUnBabWxqWVhSbExXRjFkR2h2Y21sMGVUQ0NBU0l3CkRRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNTU45NjBFTmNPS1lnQXlvbWFKc0RqV1VHeWgKYXZGQU9Bei9aL243Q3JzT1J4czJkT1EvQmU0TlMxaTI0YW5SRjNqaDdHWUM0bzIyT28yUDlIcFZWRzlhZExodQpzT01sNU00ZHhCVWtzcXV6eEFWRnhWN1J4eVlJaTRoMzJhUUY0VU1qL2gwbW9wbUNieHVzNHVPRnNJRHNDOHJvClV4RVkxdjFxcVl0NSswSjZKaDVkTjJiTGhCMllBQ0pORVdSWnFySWFMTXEwQjJoWE5razdKNnlBY0h1c1V0QnQKR3QrNHZYOGlKd0o3enMrT2RtNG5YSWdhN2RSL3g4eG1RcW9jeS9VN0diSytiUE9GYWpodUZWSGd4RWkxK3hNdwpncER1bzA0NlFFUnJRMnUrSlB2RWVxajZ0aWRrRzJndzJCb1hVQXZZeUJSVnNteVJVSGF4MjU3MlhoY0NBd0VBCkFhTVdNQlF3RWdZRFZSMFRBUUgvQkFnd0JnRUIvd0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVM0Mk0KZW5OYTZKcGtrYTlnMW5Oc09sU1NRMDFoTm15T2ZWWkFYUnJlYS8xMEVGUytiVmhCMjJLVGxsWW91NVZXRVlSdQpYTXVrQ2pYeGNCQTAweXlvMHlRMGR5S083dVVVam5rWktiOW5xVGRiS0l6d0IzZzBaUHdsL1VSbWFkTGZ3cFgxCjV4L053SnVnZHhKK3Q0OWFQeXZUbktRNTlpYmNRQi93NFR4K29nN29Db2NnSmlERVVTV09NM3ZpRmZ6a2c1K3MKSmRJN3FoM0sxbWRmNXI5T2hiMU1BZlBEQ2cwYmhtbXRDcGU5dFN1c3dUUGZ1K0dMT2VMaXJ3SVprdytPcG02TQpEY3BDRzR6NUJyMi9ZanVCcXc0QzVTLzRvQ2xOR1FKSCtjSW0vRGhmV1RXVEdFUGRSSkR3cHM0a2FCcDNIOG9sCldTUnhYLzUvTzlUeDFoZHdtdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
